use_frameworks!

target 'ValidationTextField_Example' do
  pod 'ValidationTextField', :path => '../'

  target 'ValidationTextField_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
